### ISSUE TITLE
The flaw in chapter1_supp_trpo

### ISSUE THREAD

**Issue by MarginalCentrality** [opendilab/PPOxFamily#2]
Given two functions f_1 and f_2,  f_1(x_0) = f_2(x_0) and f'_1(x_0) = f'_2(x_0), there may do not exist a ball B around x_0 such that: \forall x_1, x_2 \in B, f_1(x_2) >= f_1(x_1) \rightarrow f_2(x_2) >= f_1(x_1). 
For instance, f_1(x) = x^2, f_2(x) = -1 * x^2.

We may need more properties for this claim.

**Comment by lichuming** [comment]
Thanks for you correction! The stationary point is really a special case overlooked by us, we will fix this issue in the later versions.
