### ISSUE TITLE
Dual clipping parameter

### ISSUE THREAD

**Issue by jviquerat** [opendilab/PPOxFamily#95]
Hi,

I might be wrong, but I believe the dual clipping parameter is intended to be > 1:

![Screenshot 2024-04-26 at 18 27 03](https://github.com/opendilab/PPOxFamily/assets/44053700/399a87ed-44cf-4ece-a694-d8271101177f)

https://github.com/opendilab/PPOxFamily/blob/79761dc67ac812020c2f8908b2612a8f9a893014/chapter7_tricks/dual_clip.py#L59

**Comment by PaParaZz1** [comment]
This is indeed our problem, here the `dual_clip` value should be greater than 1.0. We are sorry about the problem when migrating code from DI-engine ([link](https://github.com/opendilab/DI-engine/blob/main/ding/rl_utils/ppo.py#L95)). We will fix this problem soon.

**Comment by PaParaZz1** [comment]
We have fixed this problem in #96.
